BEGIN;

GRANT USAGE ON SCHEMA mpi to pass_card_dev;
GRANT USAGE ON SCHEMA mpi to pass_card_srv;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA mpi TO pass_card_dev;
GRANT SELECT ON ALL TABLES IN SCHEMA mpi TO pass_card_srv;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA mpi TO pass_card_dev;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA mpi TO pass_card_srv;

COMMIT;