BEGIN;

CREATE TABLE mpi.type_feedback
(id        integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 name      varchar(100) NOT NULL,
 CONSTRAINT pk_type_feedback_id PRIMARY KEY (id)
);
comment on table mpi.type_feedback is 'Тип обратной связи';
comment on column mpi.type_feedback.id is 'Идентификатор';
comment on column mpi.type_feedback.name is 'Наименование';

CREATE TABLE mpi.feedback
(
    id                     bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email                  text NOT NULL,
    type_feedback_id       integer NOT NULL,
    message                text NOT NULL,
    user_id                bigint NULL,
    last_edit_date         timestamptz NULL,
    create_date            timestamptz NOT NULL,
    active                 boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_feedback_id PRIMARY KEY (id),
    CONSTRAINT fk_feedback_type_feedback FOREIGN KEY (type_feedback_id) REFERENCES mpi.type_feedback (id),
    CONSTRAINT fk_feedback_user FOREIGN KEY (user_id) REFERENCES mpi.user (id)
);
comment on table mpi.feedback is 'Обратная связь';
comment on column mpi.feedback.id is 'Идентификатор';
comment on column mpi.feedback.email is 'Email';
comment on column mpi.feedback.type_feedback_id is 'Тип';
comment on column mpi.feedback.message is 'Сообщение';
comment on column mpi.feedback.user_id is 'Идентификатор пользователя';
comment on column mpi.feedback.last_edit_date is 'Дата и время последнего изменения';
comment on column mpi.feedback.create_date is 'Дата и время создания';
comment on column mpi.feedback.active is 'Флаг удаления';

COMMIT;