BEGIN;

CREATE SCHEMA IF NOT EXISTS mpi;

CREATE TABLE mpi.role
(
  id                  bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name"              text NOT NULL,
  creater_id          bigint NULL,
  create_date         timestamptz NOT NULL,
  last_edit_date      timestamptz NULL,
  active              boolean NOT NULL DEFAULT false,
  CONSTRAINT pk_role_id PRIMARY KEY (id)
);
comment on table mpi.role is 'Роли пользователей';
comment on column mpi.role.id is 'Идентификатор';
comment on column mpi.role.name is 'Наименование';
comment on column mpi.role.creater_id is 'Идентификатор пользователя добавившего запись';
comment on column mpi.role.create_date is 'Дата и время создания';
comment on column mpi.role.last_edit_date is 'Дата и время последнего изменения';
comment on column mpi.role.active is 'Флаг удаления';

CREATE TABLE mpi.country
(
  id                  bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name"              text NOT NULL,
  description         text NULL,
  creater_id          bigint NULL,
  create_date         timestamptz NOT NULL,
  last_edit_date      timestamptz NULL,
  active              boolean NOT NULL DEFAULT false,
  CONSTRAINT pk_country_id PRIMARY KEY (id)
);
comment on table mpi.country is 'Справочник стран';
comment on column mpi.country.id is 'Идентификатор';
comment on column mpi.country.name is 'Наименование';
comment on column mpi.country.description is 'Описание';
comment on column mpi.country.creater_id is 'Идентификатор пользователя добавившего запись';
comment on column mpi.country.create_date is 'Дата и время создания';
comment on column mpi.country.last_edit_date is 'Дата и время последнего изменения';
comment on column mpi.country.active is 'Флаг удаления';

CREATE TABLE mpi.region
(
  id                  bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name"              text NOT NULL,
  description         text NULL,
  country_id          bigint NOT NULL,
  creater_id          bigint NULL,
  create_date         timestamptz NOT NULL,
  last_edit_date      timestamptz NULL,
  active              boolean NOT NULL DEFAULT false,
  CONSTRAINT pk_region_id PRIMARY KEY (id),
  CONSTRAINT fk_region_country FOREIGN KEY (country_id) REFERENCES mpi.country (id)
);
comment on table mpi.region is 'Справочник  областей';
comment on column mpi.region.id is 'Идентификатор';
comment on column mpi.region.name is 'Наименование';
comment on column mpi.region.description is 'Описание';
comment on column mpi.region.country_id is 'Идентификатор страны';
comment on column mpi.region.creater_id is 'Идентификатор пользователя добавившего запись';
comment on column mpi.region.create_date is 'Дата и время создания';
comment on column mpi.region.last_edit_date is 'Дата и время последнего изменения';
comment on column mpi.region.active is 'Флаг удаления';

CREATE TABLE mpi.district
(
  id                  bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name"              text NOT NULL,
  description         text NULL,
  region_id           bigint NOT NULL,
  creater_id          bigint NULL,
  create_date         timestamptz NOT NULL,
  last_edit_date      timestamptz NULL,
  active              boolean NOT NULL DEFAULT false,
  CONSTRAINT pk_district_id PRIMARY KEY (id),
  CONSTRAINT fk_district_region FOREIGN KEY (region_id) REFERENCES mpi.region (id)
);
comment on table mpi.district is 'Справочник районов';
comment on column mpi.district.id is 'Идентификатор';
comment on column mpi.district.name is 'Наименование';
comment on column mpi.district.description is 'Описание';
comment on column mpi.district.region_id is 'Идентификатор области';
comment on column mpi.district.creater_id is 'Идентификатор пользователя добавившего запись';
comment on column mpi.district.create_date is 'Дата и время создания';
comment on column mpi.district.last_edit_date is 'Дата и время последнего изменения';
comment on column mpi.district.active is 'Флаг удаления';

CREATE TABLE mpi.type_locality
(id        integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 name      varchar(100) NOT NULL,
 CONSTRAINT pk_type_locality_id PRIMARY KEY (id)
);
comment on table mpi.type_locality is 'Тип населенного пункта';
comment on column mpi.type_locality.id is 'Идентификатор';
comment on column mpi.type_locality.name is 'Наименование';

CREATE TABLE mpi.locality
(
  id                    bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name"                text NOT NULL,
  description           text NULL,
  type_locality_id      integer NOT NULL,
  region_id             bigint NOT NULL,
  district_id           bigint NULL,
  creater_id            bigint NULL,
  create_date           timestamptz NOT NULL,
  last_edit_date        timestamptz NULL,
  active                boolean NOT NULL DEFAULT false,
  CONSTRAINT pk_locality_id PRIMARY KEY (id),
  CONSTRAINT fk_locality_type_locality FOREIGN KEY (type_locality_id) REFERENCES mpi.type_locality (id),
  CONSTRAINT fk_locality_region FOREIGN KEY (region_id) REFERENCES mpi.region (id),
  CONSTRAINT fk_locality_district FOREIGN KEY (district_id) REFERENCES mpi.district (id)
);
comment on table mpi.locality is 'Справочник населенных пунктов';
comment on column mpi.locality.id is 'Идентификатор';
comment on column mpi.locality.name is 'Наименование';
comment on column mpi.locality.description is 'Описание';
comment on column mpi.locality.type_locality_id is 'Идентификатор типа населенного пункта';
comment on column mpi.locality.region_id is 'Идентификатор области';
comment on column mpi.locality.district_id is 'Идентификатор района';
comment on column mpi.locality.creater_id is 'Идентификатор пользователя добавившего запись';
comment on column mpi.locality.create_date is 'Дата и время создания';
comment on column mpi.locality.last_edit_date is 'Дата и время последнего изменения';
comment on column mpi.locality.active is 'Флаг удаления';

CREATE TABLE mpi.district_locality
(
  id                  bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name"              text NOT NULL,
  description         text NULL,
  locality_id         bigint NOT NULL,
  creater_id          bigint NULL,
  create_date         timestamptz NOT NULL,
  last_edit_date      timestamptz NULL,
  active              boolean NOT NULL DEFAULT false,
  CONSTRAINT pk_district_locality_id PRIMARY KEY (id),
  CONSTRAINT fk_district_locality_locality FOREIGN KEY (locality_id) REFERENCES mpi.locality (id)
);
comment on table mpi.district_locality is 'Справочник районов населенного пункта';
comment on column mpi.district_locality.id is 'Идентификатор';
comment on column mpi.district_locality.name is 'Наименование';
comment on column mpi.district_locality.description is 'Описание';
comment on column mpi.district_locality.locality_id is 'Идентификатор населенного пункта';
comment on column mpi.district_locality.creater_id is 'Идентификатор пользователя добавившего запись';
comment on column mpi.district_locality.create_date is 'Дата и время создания';
comment on column mpi.district_locality.last_edit_date is 'Дата и время последнего изменения';
comment on column mpi.district_locality.active is 'Флаг удаления';

CREATE TABLE mpi.street
(
  id                        bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name"                    text NOT NULL,
  description               text NULL,
  locality_id               bigint NOT NULL,
  district_locality_id      bigint NULL,
  creater_id                bigint NULL,
  create_date               timestamptz NOT NULL,
  last_edit_date            timestamptz NULL,
  active                    boolean NOT NULL DEFAULT false,
  CONSTRAINT pk_street_id PRIMARY KEY (id),
  CONSTRAINT fk_street_locality FOREIGN KEY (locality_id) REFERENCES mpi.locality (id),
  CONSTRAINT fk_street_district_locality FOREIGN KEY (district_locality_id) REFERENCES mpi.district_locality (id)
);
comment on table mpi.street is 'Справочник улиц';
comment on column mpi.street.id is 'Идентификатор';
comment on column mpi.street.name is 'Наименование';
comment on column mpi.street.description is 'Описание';
comment on column mpi.street.locality_id is 'Идентификатор населенного пункта';
comment on column mpi.street.district_locality_id is 'Идентификатор района населенного пункта';
comment on column mpi.street.creater_id is 'Идентификатор пользователя добавившего запись';
comment on column mpi.street.create_date is 'Дата и время создания';
comment on column mpi.street.last_edit_date is 'Дата и время последнего изменения';
comment on column mpi.street.active is 'Флаг удаления';

CREATE TABLE mpi.address
(
  id                        bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  country_id                bigint NOT NULL,
  region_id                 bigint NOT NULL,
  district_id               bigint NULL,
  locality_id               bigint NOT NULL,
  district_locality_id      bigint NULL,
  street_id                 bigint NOT NULL,
  home                      text NOT NULL,
  bild                      text NULL,
  flat                      text NULL,
  room                      text NULL,
  zipcode                   text NULL,
  description               text NULL,
  creater_id                bigint NULL,
  create_date               timestamptz NOT NULL,
  last_edit_date            timestamptz NULL,
  active                    boolean NOT NULL DEFAULT false,
  CONSTRAINT pk_address_id PRIMARY KEY (id),
  CONSTRAINT fk_address_country FOREIGN KEY (country_id) REFERENCES mpi.country (id),
  CONSTRAINT fk_address_region FOREIGN KEY (region_id) REFERENCES mpi.region (id),
  CONSTRAINT fk_address_district FOREIGN KEY (district_id) REFERENCES mpi.district (id),
  CONSTRAINT fk_address_locality FOREIGN KEY (locality_id) REFERENCES mpi.locality (id),
  CONSTRAINT fk_address_district_locality FOREIGN KEY (district_locality_id) REFERENCES mpi.district_locality (id),
  CONSTRAINT fk_address_street FOREIGN KEY (street_id) REFERENCES mpi.street (id)
);
comment on table mpi.address is 'Адрес';
comment on column mpi.address.id is 'Идентификатор';
comment on column mpi.address.country_id is 'Идентификатор страны';
comment on column mpi.address.region_id is 'Идентификатор области';
comment on column mpi.address.district_id is 'Идентификатор района';
comment on column mpi.address.locality_id is 'Идентификатор населенного пункта';
comment on column mpi.address.district_locality_id is 'Идентификатор района населенного пункта';
comment on column mpi.address.street_id is 'Идентификатор улицы';
comment on column mpi.address.home is 'Дом';
comment on column mpi.address.bild is 'Корпус/строение';
comment on column mpi.address.flat is 'Квартира';
comment on column mpi.address.room is 'Комната';
comment on column mpi.address.zipcode is 'Индекс';
comment on column mpi.address.description is 'Описание';
comment on column mpi.address.creater_id is 'Идентификатор пользователя добавившего запись';
comment on column mpi.address.create_date is 'Дата и время создания';
comment on column mpi.address.last_edit_date is 'Дата и время последнего изменения';
comment on column mpi.address.active is 'Флаг удаления';

CREATE TABLE mpi.user
(
  id                  bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  username            text NOT NULL,
  password            text NOT NULL,
  first_name          text NOT NULL,
  last_name           text NOT NULL,
  middle_name         text NULL,
  birth               timestamptz NOT NULL,
  photo_path          text NULL,
  email               text NOT NULL,
  description         text NULL,
  address_id          bigint NOT NULL,
  creater_id          bigint NULL,
  create_date         timestamptz NOT NULL,
  last_edit_date      timestamptz NULL,
  active              boolean NOT NULL DEFAULT false,
  CONSTRAINT pk_user_id PRIMARY KEY (id),
  CONSTRAINT fk_user_address FOREIGN KEY (address_id) REFERENCES mpi.address (id)
);
comment on table mpi.user is 'Пользователи';
comment on column mpi.user.id is 'Идентификатор';
comment on column mpi.user.username is 'Логин';
comment on column mpi.user.password is 'Пароль';
comment on column mpi.user.first_name is 'Имя';
comment on column mpi.user.last_name is 'Фамилия';
comment on column mpi.user.middle_name is 'Отчество';
comment on column mpi.user.birth is 'Дата рождения';
comment on column mpi.user.photo_path is 'Путь к фотографии';
comment on column mpi.user.email is 'Электронная почта';
comment on column mpi.user.description is 'Описание';
comment on column mpi.user.address_id is 'Идентификатор адреса';
comment on column mpi.user.creater_id is 'Идентификатор пользователя добавившего запись';
comment on column mpi.user.create_date is 'Дата и время создания';
comment on column mpi.user.last_edit_date is 'Дата и время последнего изменения';
comment on column mpi.user.active is 'Флаг удаления';

CREATE TABLE mpi.user_role
(id                bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 user_id           bigint NOT NULL,
 role_id           bigint NOT NULL,
 CONSTRAINT pk_user_role_id PRIMARY KEY (id),
 CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES mpi.user (id),
 CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES mpi.role (id)
);
comment on table mpi.user_role is 'Пропуск - Справочник видов передвижения';
comment on column mpi.user_role.id is 'Идентификатор';
comment on column mpi.user_role.user_id is 'Идентификатор пользователя';
comment on column mpi.user_role.role_id is 'Идентификатор роли';

CREATE TABLE mpi.reason_card
(
  id                  bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name"              text NOT NULL,
  description         text NULL,
  creater_id          bigint NULL,
  create_date         timestamptz NOT NULL,
  last_edit_date      timestamptz NULL,
  active              boolean NOT NULL DEFAULT false,
  CONSTRAINT pk_reason_card_id PRIMARY KEY (id)
);
comment on table mpi.reason_card is 'Справочник причины для выдачи пропуска';
comment on column mpi.reason_card.id is 'Идентификатор';
comment on column mpi.reason_card.name is 'Наименование причины для выдачи пропуска';
comment on column mpi.reason_card.description is 'Описание';
comment on column mpi.reason_card.creater_id is 'Идентификатор пользователя добавившего запись';
comment on column mpi.reason_card.create_date is 'Дата и время создания';
comment on column mpi.reason_card.last_edit_date is 'Дата и время последнего изменения';
comment on column mpi.reason_card.active is 'Флаг удаления';

CREATE TABLE mpi.type_card
(
  id                  bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name"              text NOT NULL,
  description         text NULL,
  creater_id          bigint NULL,
  create_date         timestamptz NOT NULL,
  last_edit_date      timestamptz NULL,
  active              boolean NOT NULL DEFAULT false,
  CONSTRAINT pk_type_card_id PRIMARY KEY (id)
);
comment on table mpi.type_card is 'Справочник видов передвижения';
comment on column mpi.type_card.id is 'Идентификатор';
comment on column mpi.type_card.name is 'Наименование вида передвижения';
comment on column mpi.type_card.description is 'Описание';
comment on column mpi.type_card.creater_id is 'Идентификатор пользователя добавившего запись';
comment on column mpi.type_card.create_date is 'Дата и время создания';
comment on column mpi.type_card.last_edit_date is 'Дата и время последнего изменения';
comment on column mpi.type_card.active is 'Флаг удаления';

CREATE TABLE mpi.scope_card
(
  id                  bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  country_id          bigint NOT NULL,
  region_id           bigint NOT NULL,
  district_id         bigint NULL,
  locality_id         bigint NOT NULL,
  description         text NULL,
  creater_id          bigint NULL,
  create_date         timestamptz NOT NULL,
  last_edit_date      timestamptz NULL,
  active              boolean NOT NULL DEFAULT false,
  CONSTRAINT pk_scope_card_id PRIMARY KEY (id),
  CONSTRAINT fk_scope_card_country FOREIGN KEY (country_id) REFERENCES mpi.country (id),
  CONSTRAINT fk_scope_card_region FOREIGN KEY (region_id) REFERENCES mpi.region (id),
  CONSTRAINT fk_scope_card_district FOREIGN KEY (district_id) REFERENCES mpi.district (id),
  CONSTRAINT fk_scope_card_locality FOREIGN KEY (locality_id) REFERENCES mpi.locality (id)
);
comment on table mpi.scope_card is 'Область передвижения';
comment on column mpi.scope_card.id is 'Идентификатор';
comment on column mpi.scope_card.country_id is 'Идентификатор страны';
comment on column mpi.scope_card.region_id is 'Идентификатор области';
comment on column mpi.scope_card.district_id is 'Идентификатор района';
comment on column mpi.scope_card.locality_id is 'Идентификатор населенного пункта';
comment on column mpi.scope_card.description is 'Описание';
comment on column mpi.scope_card.creater_id is 'Идентификатор пользователя добавившего запись';
comment on column mpi.scope_card.create_date is 'Дата и время создания';
comment on column mpi.scope_card.last_edit_date is 'Дата и время последнего изменения';
comment on column mpi.scope_card.active is 'Флаг удаления';

CREATE TABLE mpi.status_card
(id        integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 name      varchar(100) NOT NULL,
 CONSTRAINT pk_status_card_id PRIMARY KEY (id)
);
comment on table mpi.status_card is 'Статус пропуска';
comment on column mpi.status_card.id is 'Идентификатор';
comment on column mpi.status_card.name is 'Наименование';

CREATE TABLE mpi.pass_card
(
  id                   bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  number               uuid NOT NULL,
  status_card_id       integer NOT NULL,
  user_id              bigint NOT NULL,
  start_date           timestamptz NOT NULL,
  expiration_date      timestamptz NOT NULL,
  description          text NULL,
  creater_id           bigint NULL,
  create_date          timestamptz NOT NULL,
  last_edit_date       timestamptz NULL,
  active               boolean NOT NULL DEFAULT false,
  CONSTRAINT pk_pass_card_id PRIMARY KEY (id),
  CONSTRAINT fk_pass_card_status_card FOREIGN KEY (status_card_id) REFERENCES mpi.status_card (id),
  CONSTRAINT fk_pass_card_user FOREIGN KEY (user_id) REFERENCES mpi.user (id)
);
comment on table mpi.pass_card is 'Пропуск';
comment on column mpi.pass_card.id is 'Идентификатор';
comment on column mpi.pass_card.number is 'Номер';
comment on column mpi.pass_card.status_card_id is 'Идентификатор статуса';
comment on column mpi.pass_card.user_id is 'Идентификатор пользователя';
comment on column mpi.pass_card.start_date is 'Дата и время начала действия';
comment on column mpi.pass_card.expiration_date is 'Дата и время окончания действия';
comment on column mpi.pass_card.create_date is 'Дата и время создания';
comment on column mpi.pass_card.description is 'Описание';
comment on column mpi.pass_card.creater_id is 'Идентификатор пользователя добавившего запись';
comment on column mpi.pass_card.create_date is 'Дата и время создания';
comment on column mpi.pass_card.last_edit_date is 'Дата и время последнего изменения';
comment on column mpi.pass_card.active is 'Флаг удаления';

CREATE TABLE mpi.pass_card_reason_card
(id             bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 pass_card_id      bigint NOT NULL,
 reason_card_id      bigint NOT NULL,
 CONSTRAINT pk_pass_card_reason_card_id PRIMARY KEY (id),
 CONSTRAINT fk_pass_card_reason_card_pass_card FOREIGN KEY (pass_card_id) REFERENCES mpi.pass_card (id),
 CONSTRAINT fk_pass_card_reason_card_reason_card FOREIGN KEY (reason_card_id) REFERENCES mpi.reason_card (id)
);
comment on table mpi.pass_card_reason_card is 'Пропуск - Справочник причины для выдачи пропуска';
comment on column mpi.pass_card_reason_card.id is 'Идентификатор';
comment on column mpi.pass_card_reason_card.pass_card_id is 'Идентификатор пропуска';
comment on column mpi.pass_card_reason_card.reason_card_id is 'Идентификатор причины для выдачи пропуска';

CREATE TABLE mpi.pass_card_scope_card
(id                 bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 pass_card_id       bigint NOT NULL,
 scope_card_id      bigint NOT NULL,
 CONSTRAINT pk_pass_card_scope_card_id PRIMARY KEY (id),
 CONSTRAINT fk_pass_card_scope_card_pass_card FOREIGN KEY (pass_card_id) REFERENCES mpi.pass_card (id),
 CONSTRAINT fk_pass_card_scope_card_scope_card FOREIGN KEY (scope_card_id) REFERENCES mpi.scope_card (id)
);
comment on table mpi.pass_card_scope_card is 'Пропуск - Область передвижения';
comment on column mpi.pass_card_scope_card.id is 'Идентификатор';
comment on column mpi.pass_card_scope_card.pass_card_id is 'Идентификатор пропуска';
comment on column mpi.pass_card_scope_card.scope_card_id is 'Идентификатор области передвижения';

CREATE TABLE mpi.pass_card_type_card
(id                bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 pass_card_id      bigint NOT NULL,
 type_card_id      bigint NOT NULL,
 CONSTRAINT pk_pass_card_type_card_id PRIMARY KEY (id),
 CONSTRAINT fk_pass_card_type_card_pass_card FOREIGN KEY (pass_card_id) REFERENCES mpi.pass_card (id),
 CONSTRAINT fk_pass_card_type_card_type_card FOREIGN KEY (type_card_id) REFERENCES mpi.type_card (id)
);
comment on table mpi.pass_card_type_card is 'Пропуск - Справочник видов передвижения';
comment on column mpi.pass_card_type_card.id is 'Идентификатор';
comment on column mpi.pass_card_type_card.pass_card_id is 'Идентификатор пропуска';
comment on column mpi.pass_card_type_card.type_card_id is 'Идентификатор вида передвижения';

CREATE TABLE mpi.type_feedback
(id        integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 name      varchar(100) NOT NULL,
 CONSTRAINT pk_type_feedback_id PRIMARY KEY (id)
);
comment on table mpi.type_feedback is 'Тип обратной связи';
comment on column mpi.type_feedback.id is 'Идентификатор';
comment on column mpi.type_feedback.name is 'Наименование';

CREATE TABLE mpi.feedback
(
  id                     bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  email                  text NOT NULL,
  type_feedback_id       integer NOT NULL,
  message                text NOT NULL,
  creater_id             bigint NULL,
  create_date            timestamptz NOT NULL,
  last_edit_date         timestamptz NULL,
  active                 boolean NOT NULL DEFAULT true,
  CONSTRAINT pk_feedback_id PRIMARY KEY (id),
  CONSTRAINT fk_feedback_type_feedback FOREIGN KEY (type_feedback_id) REFERENCES mpi.type_feedback (id),
  CONSTRAINT fk_feedback_user FOREIGN KEY (creater_id) REFERENCES mpi.user (id)
);
comment on table mpi.feedback is 'Обратная связь';
comment on column mpi.feedback.id is 'Идентификатор';
comment on column mpi.feedback.email is 'Email';
comment on column mpi.feedback.type_feedback_id is 'Тип';
comment on column mpi.feedback.message is 'Сообщение';
comment on column mpi.feedback.creater_id is 'Идентификатор пользователя добавившего запись';
comment on column mpi.feedback.create_date is 'Дата и время создания';
comment on column mpi.feedback.last_edit_date is 'Дата и время последнего изменения';
comment on column mpi.feedback.active is 'Флаг удаления';

CREATE TABLE mpi.priority
(id        integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 name      varchar(100) NOT NULL,
 CONSTRAINT pk_priority_news_id PRIMARY KEY (id)
);
comment on table mpi.priority is 'Приоритет';
comment on column mpi.priority.id is 'Идентификатор';
comment on column mpi.priority.name is 'Наименование';

CREATE TABLE mpi.news
(
  id                     bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  title                  text NOT NULL,
  body                   text NOT NULL,
  news_date              timestamptz NULL,
  priority_id            integer NULL,
  description            text NULL,
  creater_id             bigint NULL,
  create_date            timestamptz NOT NULL,
  last_edit_date         timestamptz NULL,
  active                 boolean NOT NULL DEFAULT true,
  CONSTRAINT pk_news_id PRIMARY KEY (id),
  CONSTRAINT fk_news_priority FOREIGN KEY (priority_id) REFERENCES mpi.priority (id),
  CONSTRAINT fk_news_creater FOREIGN KEY (creater_id) REFERENCES mpi.user (id)
);
comment on table mpi.news is 'Новость';
comment on column mpi.news.id is 'Идентификатор';
comment on column mpi.news.title is 'Заголовок';
comment on column mpi.news.body is 'Тело';
comment on column mpi.news.news_date is 'Дата новости';
comment on column mpi.news.priority_id is 'Идентификатор приоритета';
comment on column mpi.news.description is 'Описание';
comment on column mpi.news.creater_id is 'Идентификатор пользователя добавившего запись';
comment on column mpi.news.create_date is 'Дата и время создания';
comment on column mpi.news.last_edit_date is 'Дата и время последнего изменения';
comment on column mpi.news.active is 'Флаг удаления';

CREATE TABLE mpi.news_author
(id                bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 news_id      bigint NOT NULL,
 author_id      bigint NOT NULL,
 CONSTRAINT pk_news_author_id PRIMARY KEY (id),
 CONSTRAINT fk_news_author_news FOREIGN KEY (news_id) REFERENCES mpi.news (id),
 CONSTRAINT fk_news_author_author FOREIGN KEY (author_id) REFERENCES mpi.user (id)
);
comment on table mpi.news_author is 'Новость - Автор';
comment on column mpi.news_author.id is 'Идентификатор';
comment on column mpi.news_author.news_id is 'Идентификатор новости';
comment on column mpi.news_author.author_id is 'Идентификатор автора';

CREATE TABLE mpi.link
(
  id                     bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name                   text NOT NULL,
  value                  text NOT NULL,
  news_id                bigint NOT NULL,
  description            text NULL,
  creater_id             bigint NULL,
  create_date            timestamptz NOT NULL,
  last_edit_date         timestamptz NULL,
  active                 boolean NOT NULL DEFAULT true,
  CONSTRAINT pk_link_id PRIMARY KEY (id),
  CONSTRAINT fk_link_news FOREIGN KEY (news_id) REFERENCES mpi.news (id),
  CONSTRAINT fk_link_creater FOREIGN KEY (creater_id) REFERENCES mpi.user (id)
);
comment on table mpi.link is 'Ссылка';
comment on column mpi.link.id is 'Идентификатор';
comment on column mpi.link.name is 'Имя';
comment on column mpi.link.value is 'Значение';
comment on column mpi.link.news_id is 'Идентификатор новости';
comment on column mpi.link.description is 'Описание';
comment on column mpi.link.creater_id is 'Идентификатор пользователя добавившего запись';
comment on column mpi.link.create_date is 'Дата и время создания';
comment on column mpi.link.last_edit_date is 'Дата и время последнего изменения';
comment on column mpi.link.active is 'Флаг удаления';

CREATE TABLE mpi.guide
(
  id                     bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  title                  text NOT NULL,
  body                   text NOT NULL,
  attachment             text NOT NULL,
  description            text NULL,
  creater_id             bigint NULL,
  create_date            timestamptz NOT NULL,
  last_edit_date         timestamptz NULL,
  active                 boolean NOT NULL DEFAULT true,
  CONSTRAINT pk_guide_id PRIMARY KEY (id),
  CONSTRAINT fk_guide_creater FOREIGN KEY (creater_id) REFERENCES mpi.user (id)
);
comment on table mpi.guide is 'Руководство';
comment on column mpi.guide.id is 'Идентификатор';
comment on column mpi.guide.title is 'Заголовок';
comment on column mpi.guide.body is 'Тело';
comment on column mpi.guide.attachment is 'Вложенность';
comment on column mpi.guide.description is 'Описание';
comment on column mpi.guide.creater_id is 'Идентификатор пользователя добавившего запись';
comment on column mpi.guide.create_date is 'Дата и время создания';
comment on column mpi.guide.last_edit_date is 'Дата и время последнего изменения';
comment on column mpi.guide.active is 'Флаг удаления';

CREATE TABLE mpi.about
(
  id                     bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  title                  text NOT NULL,
  body                   text NOT NULL,
  description            text NULL,
  creater_id             bigint NULL,
  create_date            timestamptz NOT NULL,
  last_edit_date         timestamptz NULL,
  active                 boolean NOT NULL DEFAULT true,
  CONSTRAINT pk_about_id PRIMARY KEY (id),
  CONSTRAINT fk_about_creater FOREIGN KEY (creater_id) REFERENCES mpi.user (id)
);
comment on table mpi.about is 'Информация о нас';
comment on column mpi.about.id is 'Идентификатор';
comment on column mpi.about.title is 'Заголовок';
comment on column mpi.about.body is 'Тело';
comment on column mpi.about.description is 'Описание';
comment on column mpi.about.creater_id is 'Идентификатор пользователя добавившего запись';
comment on column mpi.about.create_date is 'Дата и время создания';
comment on column mpi.about.last_edit_date is 'Дата и время последнего изменения';
comment on column mpi.about.active is 'Флаг удаления';

CREATE TABLE mpi.mes_name
(id        integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 name      varchar(100) NOT NULL,
 CONSTRAINT pk_mes_name_id PRIMARY KEY (id)
);
comment on table mpi.mes_name is 'Приоритет новости';
comment on column mpi.mes_name.id is 'Идентификатор';
comment on column mpi.mes_name.name is 'Наименование';

CREATE TABLE mpi.contact
(
  id                     bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  mes_name_id            integer NOT NULL,
  value                  text NOT NULL,
  description            text NULL,
  creater_id             bigint NULL,
  create_date            timestamptz NOT NULL,
  last_edit_date         timestamptz NULL,
  active                 boolean NOT NULL DEFAULT true,
  CONSTRAINT pk_contact_id PRIMARY KEY (id),
  CONSTRAINT fk_contact_creater FOREIGN KEY (creater_id) REFERENCES mpi.user (id)
);
comment on table mpi.contact is 'Ссылка';
comment on column mpi.contact.id is 'Идентификатор';
comment on column mpi.contact.mes_name_id is 'Идентификатор имени';
comment on column mpi.contact.value is 'Значение';
comment on column mpi.contact.description is 'Описание';
comment on column mpi.contact.creater_id is 'Идентификатор пользователя добавившего запись';
comment on column mpi.contact.create_date is 'Дата и время создания';
comment on column mpi.contact.last_edit_date is 'Дата и время последнего изменения';
comment on column mpi.contact.active is 'Флаг удаления';

COMMIT;